image: Ubuntu

version: '6.0.0.{build}'

dotnet_csproj:
  version_prefix: '6.0.0'
  patch: true
  file: 'src\**\*.csproj'

configuration: Release

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

skip_tags: true

nuget:
  disable_publish_on_pr: true

clone_depth: 1

test: off

build_script:
  - pwsh: .\build.ps1
  # Download the latest version of WhiteSource FS Agent
  - curl -LJO https://github.com/whitesource/fs-agent-distribution/raw/master/standAlone/whitesource-fs-agent.jar
  # Download the default configuration file
  - curl -LJO https://github.com/whitesource/fs-agent-distribution/raw/master/standAlone/whitesource-fs-agent.config
  # Replace the flags in the configuration to enable policy check
  - cat whitesource-fs-agent.config | sed -e "s/forceCheckAllDependencies=false/forceCheckAllDependencies=true/" > temp_file.config
  # Copy the new configuration file over the original file
  - mv temp_file.config whitesource-fs-agent.config
  # Run WhiteSource FS Agent
  - java -jar whitesource-fs-agent.jar -apiKey 41c71f81b00e4ec5868fece050113260fa23031c6fac460a81945a99bfaeea51 -product mytest -c whitesource-fs-agent.config -d . -project Autofac

artifacts:
- path: artifacts\packages\**\*.nupkg
  name: MyGet

deploy:
- provider: NuGet
  server: https://www.myget.org/F/autofac/api/v2/package
  api_key:
    secure: rCUEY75fXN0wxtMy6QL4jCrLdaYbxIBzIXWeN+wEu/XDpyqimzreOc5AH5jMd5ah
  skip_symbols: true
  symbol_server: https://www.myget.org/F/autofac/symbols/api/v2/package
  artifact: MyGet
on_success:
- curl -s -o upload https://copilot.blackducksoftware.com/ci/appveyor/scripts/upload
- bash upload
- curl -s https://scripts.scantist.com/staging/scantist-bom-detect.jar --output scantist-bom-detect.jar
- java -jar scantist-bom-detect.jar -repo_name $Autofac
